name: gpu_info
description: "A Flutter plugin to access GPU information."
version: 0.0.1
repository: 'https://github.com/WilliamKarolDiCioccio/gpu_info'
issue_tracker: 'https://github.com/WilliamKarolDiCioccio/gpu_info/issues'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: GpuInfoPluginCApi
